<?php

namespace AppBundle\Repository;

/**
 * ApprenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprenantRepository extends \Doctrine\ORM\EntityRepository
{
}
