<?php

namespace AppBundle\Repository;

/**
 * ForumSujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumSujetRepository extends \Doctrine\ORM\EntityRepository
{
}
