<?php

namespace AppBundle\Repository;

/**
 * ForumReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
