formation_index:
    path:     /
    defaults: { _controller: "AppBundle:Formation:index" }
    methods:  GET

formation_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Formation:show" }
    methods:  GET



