forumreponse_index:
    path:     /
    defaults: { _controller: "AppBundle:ForumReponse:index" }
    methods:  GET

forumreponse_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ForumReponse:show" }
    methods:  GET



