inscription_index:
    path:     /
    defaults: { _controller: "AppBundle:Inscription:index" }
    methods:  GET

inscription_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Inscription:show" }
    methods:  GET



