apprenant_index:
    path:     /
    defaults: { _controller: "AppBundle:Apprenant:index" }
    methods:  GET

apprenant_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Apprenant:show" }
    methods:  GET

apprenant_new:
    path:     /new
    defaults: { _controller: "AppBundle:Apprenant:new" }
    methods:  [GET, POST]

apprenant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Apprenant:edit" }
    methods:  [GET, POST]

apprenant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Apprenant:delete" }
    methods:  DELETE
